name: pickit
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  location: ^3.0.2
  google_maps_flutter: ^1.0.6
  rxdart: ^0.24.1
  provider: ^4.3.2+2
  http: ^0.12.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

